env: "local" # local, dev, prod
storage_path: "./storage/storage.db"
http_server:
  address : "localhost:8081"
  timeout: 4s
  idle_timeout: 60s
  user: "myuser"
  password: "mypass"
clients:
  sso:
    address: "localhost:44044"
    timeout: 1m
    retries_count: 3